export const LOGIN_URL = process.env.NODE_ENV === 'prodaction' ? "/api-user/oauth/token" : "/api-user/oauth/token";

export const SAVE_FIELD_URL = "/xms/page/saveOrUpdatePage";

export const SAVE_PICTURE_URL = "/xms/page/uploadPicture"

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const FETCH_PWDINFO = "FETCH_PWDINFO";

export const FETCH_MAIN_START = "FETCH_MAIN_START";
export const FETCH_MAIN_SUCCESS = "FETCH_MAIN_SUCCESS";
export const FETCH_MAIN_ERROR = "FETCH_MAIN_ERROR";

export const FETCH_LIST_START = "FETCH_LIST_START";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_ERROR = "FETCH_LIST_ERROR";

export const DELETE_LIST_START = "DELETE_LIST_START";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_ERROR = "DELETE_LIST_ERROR";

export const FETCH_TABLEVIEW_START = "FETCH_TABLEVIEW_START";
export const FETCH_TABLEVIEW_SUCCESS = "FETCH_TABLEVIEW_SUCCESS";
export const FETCH_TABLEVIEW_ERROR = "FETCH_TABLEVIEW_ERROR";

export const FETCH_LISTPOPFORM_START = "FETCH_LISTPOPFORM_START";
export const FETCH_LISTPOPFORM_SUCCESS = "FETCH_LISTPOPFORM_SUCCESS";
export const FETCH_LISTPOPFORM_ERROR = "FETCH_LISTPOPFORM_ERROR";

export const FETCH_CONTRACTREPORTPAGE_START = "FETCH_CONTRACTREPORTPAGE_START";
export const FETCH_CONTRACTREPORTPAGE_SUCCESS = "FETCH_CONTRACTREPORTPAGE_SUCCESS";
export const FETCH_CONTRACTREPORTPAGE_ERROR = "FETCH_CONTRACTREPORTPAGE_ERROR";

export const FETCH_DEPREPORT_START = "FETCH_DEPREPORT_START";
export const FETCH_DEPREPORT_SUCCESS = "FETCH_DEPREPORT_SUCCESS";
export const FETCH_DEPREPORT_ERROR = "FETCH_DEPREPORT_ERROR";

export const FETCH_DETAIL_START = "FETCH_DETAIL_START";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_ERROR = "FETCH_DETAIL_ERROR";

export const FETCH_RELATION_START = "FETCH_RELATION_START";
export const FETCH_RELATION_SUCCESS = "FETCH_RELATION_SUCCESS";
export const FETCH_RELATION_ERROR = "FETCH_RELATION_ERROR";

export const FETCH_DETAILSPE_START = "FETCH_DETAILSPE_START";
export const FETCH_DETAILSPE_SUCCESS = "FETCH_DETAILSPE_SUCCESS";
export const FETCH_DETAILSPE_ERROR = "FETCH_DETAILSPE_ERROR";

export const FETCH_FLOWINSTANCELOGS_START = "FETCH_FLOWINSTANCELOGS_START";
export const FETCH_FLOWINSTANCELOGS_SUCCESS = "FETCH_FLOWINSTANCELOGS_SUCCESS";
export const FETCH_FLOWINSTANCELOGS_ERROR = "FETCH_FLOWINSTANCELOGS_ERROR";

export const SUBMIT_CHANGEFLOWSTATUS_START = "SUBMIT_CHANGEFLOWSTATUS_START";
export const SUBMIT_CHANGEFLOWSTATUS_SUCCESS = "SUBMIT_CHANGEFLOWSTATUS_SUCCESS";
export const SUBMIT_CHANGEFLOWSTATUS_ERROR = "SUBMIT_CHANGEFLOWSTATUS_ERROR";

export const FETCH_EDIT_START = "FETCH_EDIT_START";
export const FETCH_EDIT_SUCCESS = "FETCH_EDIT_SUCCESS";
export const FETCH_EDIT_ERROR = "FETCH_EDIT_ERROR";

export const SAVE_EDITINPUTINFO_START = "SAVE_EDITINPUTINFO_START";
export const SAVE_EDITINPUTINFO_SUCCESS = "SAVE_EDITINPUTINFO_SUCCESS";
export const SAVE_EDITINPUTINFO_ERROR = "SAVE_EDITINPUTINFO_ERROR";

export const FETCH_POPFORM_START = "FETCH_POPFORM_START";
export const FETCH_POPFORM_SUCCESS = "FETCH_POPFORM_SUCCESS";
export const FETCH_POPFORM_ERROR = "FETCH_POPFORM_ERROR";

export const SAVE_POPFORM_START = "SAVE_POPFORM_START";
export const SAVE_POPFORM_SUCCESS = "SAVE_POPFORM_SUCCESS";
export const SAVE_POPFORM_ERROR = "SAVE_POPFORM_ERROR";

export const DELETE_START = "DELETE_START";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_ERROR = "DELETE_ERROR";
export const DELETE_RESET = "DELETE_RESET";

export const SAVEORUPDATE_START = "SAVEORUPDATE_START";
export const SAVEORUPDATE_SUCCESS = "SAVEORUPDATE_SUCCESS";
export const SAVEORUPDATE_ERROR = "SAVEORUPDATE_ERROR";

export const FETCH_OFFERDETAIL_START = "FETCH_OFFERDETAIL_START";
export const FETCH_OFFERDETAIL_SUCCESS = "FETCH_OFFERDETAIL_SUCCESS";
export const FETCH_OFFERDETAIL_ERROR = "FETCH_OFFERDETAIL_ERROR";

export const FETCH_OFFERTABS_START = "FETCH_OFFERTABS_START";
export const FETCH_OFFERTABS_SUCCESS = "FETCH_OFFERTABS_SUCCESS";
export const FETCH_OFFERTABS_ERROR = "FETCH_OFFERTABS_ERROR";

export const FETCH_PAGEFORMSETTING_START = "FETCH_PAGEFORMSETTING_START";
export const FETCH_PAGEFORMSETTING_SUCCESS = "FETCH_PAGEFORMSETTING_SUCCESS";
export const FETCH_PAGEFORMSETTING_ERROR = "FETCH_PAGEFORMSETTING_ERROR";

export const SAVE_PAGEFORMSETTING_START = "SAVE_PAGEFORMSETTING_START";
export const SAVE_PAGEFORMSETTING_SUCCESS = "SAVE_PAGEFORMSETTING_SUCCESS";
export const SAVE_PAGEFORMSETTING_ERROR = "SAVE_PAGEFORMSETTING_ERROR";


